// Secret names auto-bootstrapped at startup or managed by the platform.
// These are shown in the "Internal" tab and are read-only.
export const INTERNAL_SECRET_NAMES = new Set([
  // added via RPC (auth_init)
  'auth_token',
  // per-project LLM key managed by runtime_interface_litellm
  'project_llm_key',
]);

// UUID4 hex pattern — secrets generated by SecretString.store_secret() for
// configuration credential fields. These are internal references, not user secrets.
const HEX_SECRET_RE = /^[0-9a-f]{32}$/;

/** Returns true if a secret name should be classified as internal. */
export const isInternalSecret = (name) =>
  INTERNAL_SECRET_NAMES.has(name) || HEX_SECRET_RE.test(name);

export const SECRET_NAME_REGEX = /^[A-Za-z0-9_]+$/;
