export const RouteDefinitions = {
  Users: "/users",
  Roles: "/roles",
  Projects: "/projects",
  Budgets: "/budgets",
  PlatformDimensions: "/platform-dimensions",
  Secrets: "/secrets",
  LiteLLM: "/litellm",
  AppRequests: "/app-requests",
  AuditTrail: "/audit-trail",
  SchedulesTasks: "/schedules-tasks",
  Configuration: "/configuration",
  Features: "/features",
  Reports: "/reports",
};
