import { INTERNAL_SECRET_NAMES } from '@/pages/SecretsPage/constants/secrets.constants';

// UUID4 hex pattern — secrets generated by SecretString.store_secret() for
// configuration credential fields. These are internal references, not user secrets.
const HEX_SECRET_RE = /^[0-9a-f]{32}$/;

/** Returns true if a secret name should be classified as internal. */
export const isInternalSecret = name => INTERNAL_SECRET_NAMES.has(name) || HEX_SECRET_RE.test(name);
