name: Auto-Increment Version

on:
  workflow_run:
    workflows: ["Build"]
    types: [completed]
    branches: [main, 'release/**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  versioneer:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: EliteaAI/actions/.github/workflows/versioneer.yml@main
    with:
      metadata_file: "metadata.json"
      version_key: ".version"
